/*
# Add anon SELECT policy for admin-media storage bucket

## Problem
The admin-media storage bucket is private (public=false) with an
authenticated-only SELECT policy. The app uses the anon key (passcode-based
admin, no Supabase auth session), so createSignedUrl() and direct downloads
fail because anon cannot read from the bucket.

## Fix
Add an anon SELECT policy for the admin-media bucket, matching the existing
anon INSERT policy. This allows the anon-key Supabase client to:
- Generate signed URLs for private media display
- Download private media blobs for original-quality downloads

## Security
- The bucket remains private (public=false) — public URLs still don't work.
- Signed URLs are time-limited (60 seconds) and can only be generated by
  callers with the anon key (which is the app itself).
- The admin_media TABLE RLS is unchanged — anon still cannot query the table
  directly. All table access goes through SECURITY DEFINER functions that
  validate the admin passcode server-side.
- The URL stored in admin_media.url is the public URL format but the bucket
  is private, so the URL alone doesn't grant access — only signed URLs work.
- Private Capture mode (isPrivateCaptureEnabled) gates all access in the
  frontend: fetchAdminMedia, download, preview all check this flag first.
*/

DROP POLICY IF EXISTS "anon_read_admin_media_storage" ON storage.objects;
CREATE POLICY "anon_read_admin_media_storage" ON storage.objects FOR SELECT
  TO anon, authenticated USING (bucket_id = 'admin-media');